blueprint:
  name: Sonoff Zigbee Button
  description: Setup actions for three functions of the SONOFF Zigbee button with
    Press, Double Press, and Hold.
  domain: automation
  input:
    button_device:
      name: Button Device (ZHA)
      description: Select the button device (for ZHA integration). Leave empty if using Zigbee2MQTT.
      default: null
      selector:
        device:
          filter:
          - manufacturer: eWeLink
            model: WB01
            integration: zha
          - manufacturer: eWeLink
            model: SNZB-01P
            integration: zha
          multiple: false
    button_action:
      name: Button Action Entity (Zigbee2MQTT)
      description: Select the action sensor entity (for Zigbee2MQTT). Leave empty if using ZHA.
      default: null
      selector:
        entity:
          filter:
          - domain: sensor
            device_class: enum
          multiple: false
    mode:
      name: Automation mode
      description: The automation’s mode configuration option controls what happens when the automation is triggered while the actions
        are still running from a previous trigger (see [Automation modes](https://www.home-assistant.io/docs/automation/modes/)).
      default: single
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
    press_action:
      name: Press Action
      description: Action to perform on Press.
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to perform on Double Press.
      default: []
      selector:
        action: {}
    hold_action:
      name: Hold Action
      description: Action to perform on Hold.
      default: []
      selector:
        action: {}
  source_url: https://github.com/apollo1220/blueprints/blob/main/sonoff_zigbee_button.yaml
variables:
  button_device: !input 'button_device'
  button_action: !input 'button_action'
mode: !input 'mode'
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'button_device'
    command: "toggle"
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'button_device'
    command: "on"
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'button_device'
    command: "off"
- platform: state
  entity_id: !input 'button_action'
  to: "single"
- platform: state
  entity_id: !input 'button_action'
  to: "double"
- platform: state
  entity_id: !input 'button_action'
  to: "hold"
- platform: state
  entity_id: !input 'button_action'
  to: "long"
action:
- choose:
  - conditions:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ trigger.platform == "event" and trigger.event.data.command == "toggle" }}'
      - condition: template
        value_template: '{{ trigger.platform == "state" and trigger.to_state.state == "single" }}'
    sequence: !input 'press_action'
  - conditions:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ trigger.platform == "event" and trigger.event.data.command == "on" }}'
      - condition: template
        value_template: '{{ trigger.platform == "state" and trigger.to_state.state == "double" }}'
    sequence: !input 'double_press_action'
  - conditions:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ trigger.platform == "event" and trigger.event.data.command == "off" }}'
      - condition: template
        value_template: '{{ trigger.platform == "state" and (trigger.to_state.state == "hold" or trigger.to_state.state == "long") }}'
    sequence: !input 'hold_action'
